### ISSUE TITLE
Add support for x5c field in /jwks

### ISSUE THREAD

**Issue by patcon** [axa-group/oauth2-mock-server#187]
## Summary

A production server we're integrating with has an x5c field in the /jwks key entries, which is being used to validate tokens. It would be amazing to understand how to alllow this to work in the mock server as well :)

## Desired solution

Support an `x5c` key within the `/jwks` list.

## Alternative solutions

I'm really new to oauth2/openid, so I'm just barely grasping this first option. Sorry!

## Additional Context

https://curity.io/resources/learn/self-contained-jwts/#x5c

**Comment by nulltoken** [comment]
@patcon 👋  Thanks for raising this.

Few thoughts:
- Bringing in certificates comes with a tons of new kind of problems, one of which being "signing the certificate". Those certs would be considered as self-signed, and, by default, not trusted by the consumer jwt validation tool/code. So it means that exposing x5c fields would require some additional configuration to explicitly trust the fake signing entity.
- I've worked with x5c some years ago, and as far as I remember that wasn't the sweetest experience of my life 😉 Then we got rid of those fields and the validation process became easier, mainly because, back in that period, no library was implementing an off-the-shelf x5c validation process. What happened on that front, is `x5c` field now widely supported by jwt validation libraries or do people still rely on hand crafted validation?
- Do we have any information regarding usage of `x5c`? Is that still a thing? Is it widely used?

**Comment by patcon** [comment]
Thanks so much for the prompt reply @nulltoken! (great handle btw haha)

I actually started a discussion (in part influenced by your comment) about removing our reliance on the x5c property: https://github.com/GCTC-NTGC/gc-digital-talent/issues/2716

Thanks for the supportive prompt questions, and for all your work on this lib. For now, I'm leaning toward a more turn-key mock server written in java and runnable in a docker container. But I suspect if we outgrow that one and need to customize, I'll end up back here rather than diving deep into Java :)

Thanks again! Will close this, but pls do re-open if you'd like to keep this feature request around
